name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv (includes caching)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.6"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run basedpyright
        run: uv run basedpyright

      - name: Run tests
        run: uv run pytest -q tests

